---
- name: "initialize packages for pi"
  hosts: "all"
  become: true
  vars:
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: "install base deps"
      apt:
        name:
          - nano
          - raspi-config
          - iputils-ping
          - dnsutils
          - net-tools
          - ethtool
          - traceroute  
          - unattended-upgrades
          - needrestart
          - tmux
          - acl
          - apt-transport-https
          - raspi-config
        state: "present"

    - name: "Remove unused packages"
      apt:
        name:
          - "ed"
          - "vim*"
          - "alsa*"
          - "modemmanager" 
          - "avahi*"
        state: "absent"

    - name: "Upgrade all packages on servers."
      apt:
        upgrade: "dist"

    - name: "Remove useless packages from the cache"
      apt:
        autoclean: true

    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: true

    - name: "Check if a reboot is needed on all servers."
      stat:
        path: "/var/run/reboot-required"
      register: "reboot_required_file"

    - name: "Reboot the box if kernel updated"
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 10
        test_command: "uptime"
      when: "reboot_required_file.stat.exists"