# https://github.com/raspberrypi/rpi-swap/tree/main
---
- name: "install rpi swap"
  hosts: "all"
  become: true
  vars:
    config_file: "/etc/rpi/swap.conf.d/swap.conf"
    multiline: |
      [File]
      MaxSizeMiB=4096

  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    
    - name: "install pipx deps"
      apt:
        name:
          - rpi-swap
          - rpi-loop-utils
        state: "present"

    - name: "create config directory"
      file:
        path: /etc/rpi/swap.conf.d
        state: directory
        mode: '0755'

    - name: "configure rpi swap"
      copy:
        dest: "{{ config_file }}"
        content: "{{ multiline }}"

    - name: "Check if a reboot is needed on all servers."
      stat:
        path: "/var/run/reboot-required"
      register: "reboot_required_file"

    - name: "Reboot the box if kernel updated"
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 10
        test_command: "uptime"
      when: "reboot_required_file.stat.exists"